### ISSUE TITLE
Social Media Card

### ISSUE THREAD

**Issue by Parzzix** [picosh/pico#66]
Just trying to figure out the syntax for the social media car in the _readme.md. Currently, I have the below, of course it did not work.. I'm assuming I have to use different syntax 

```
---
title: Parzzix
description: Tech, Privacy, Decentralization, and General Nerdiness ( proven02d4df )
nav:
    - About: https://parzzix.prose.sh/about
    - Now: https://parzzix.prose.sh/now
    - Uses: https://parzzix.prose.sh/uses
    - Github: https://github.com/Parzzix
    - Mail: mailto://parzzix@parzzix.com
card: https://media.social.lol/accounts/avatars/111/648/322/094/447/790/original/6955629621a97c14.jpeg
---
```
